server:
  port: 10201

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.3:8848
        namespace: 0966af52-a286-46a5-a5cc-0413683e7893

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.3:3306/dataintegration?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#配置MyBatis
mybatis:
  mapper-locations: classpath*:com/youngdatafan/portal/common/group/**/*Mapper.xml
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
