server:
  port: 10210

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.3:8848
        namespace: 0966af52-a286-46a5-a5cc-0413683e7893
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.3:3306/dataintegration?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  redis:
    host: 192.168.0.3
    port: 6379
    password: 123456
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 1 # 连接池中的最小空闲连接
  cache:
    type: redis

#配置MyBatis
mybatis:
  mapper-locations: classpath*:com/youngdatafan/dataintegration/file/management/mapping/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#ftp:
#  server: 127.0.0.1
#  port: 20021
#  userName: prime
#  password: prime@2020
#  passiveMode: true
#  ftpEncoding: utf-8
#10.242.10.170:30021


#文件存储类型
file:
  server:
    useServer: minio
    extendsFileType: minio
    minIos3:
      server: 192.168.0.3
      port: 9000
      url: http://192.168.0.3:9000
      accessKey: BOT1B02JT5TVX3AS8QKB
      secretKey: aOuyKjdrS6DVlhgvFpk6gi7UC6fKZI8GCsA2SHo6
      bucketName: wishdata
      rootPath: s3://

logging:
  file:
    # 配置日志目录，logbak.xml使用
    path: ./logs/${spring.application.name}
    # springboot admin获取日志使用
    name: ${logging.file.path}/all/${spring.application.name}.log

